/**
 * GENERATED by scripts/backtest-chart-data.mjs from the product's
 * research/shipped_backtest.csv. Do not edit by hand; regenerate.
 *
 * Every trade The 98¢ Trade would have made on Polymarket, as shipped, grouped
 * by the quarter the market settled in. `lostAt` is the position of each
 * losing trade within its quarter, in settlement order.
 */
export type BacktestQuarter = {
  year: number;
  quarter: number;
  trades: number;
  /** Average return per trade, in percent, before real-world fill effects. */
  avgReturnPct: number;
  lostAt: number[];
  /** The last settlement date in the data for this quarter. */
  through: string;
};

export const BACKTEST_TOTAL = { trades: 8318, lost: 80, avgReturnPct: 0.58 } as const;

export const BACKTEST_QUARTERS: BacktestQuarter[] = [
  {
    "year": 2025,
    "quarter": 1,
    "trades": 559,
    "avgReturnPct": 0.29,
    "lostAt": [
      175,
      222,
      311,
      466,
      483,
      485,
      489
    ],
    "through": "2025-03-31"
  },
  {
    "year": 2025,
    "quarter": 2,
    "trades": 782,
    "avgReturnPct": 0.55,
    "lostAt": [
      97,
      201,
      204,
      235,
      438,
      526,
      709
    ],
    "through": "2025-06-30"
  },
  {
    "year": 2025,
    "quarter": 3,
    "trades": 536,
    "avgReturnPct": 0.42,
    "lostAt": [
      18,
      57,
      62,
      190,
      412,
      458
    ],
    "through": "2025-09-30"
  },
  {
    "year": 2025,
    "quarter": 4,
    "trades": 1654,
    "avgReturnPct": 0.62,
    "lostAt": [
      74,
      83,
      553,
      789,
      868,
      870,
      970,
      980,
      1034,
      1070,
      1072,
      1073,
      1089,
      1175
    ],
    "through": "2025-12-31"
  },
  {
    "year": 2026,
    "quarter": 1,
    "trades": 1751,
    "avgReturnPct": 0.38,
    "lostAt": [
      267,
      371,
      401,
      475,
      616,
      631,
      634,
      641,
      642,
      681,
      780,
      781,
      821,
      826,
      913,
      1056,
      1084,
      1105,
      1400,
      1413,
      1728
    ],
    "through": "2026-03-31"
  },
  {
    "year": 2026,
    "quarter": 2,
    "trades": 1731,
    "avgReturnPct": 0.57,
    "lostAt": [
      143,
      223,
      300,
      369,
      583,
      683,
      727,
      820,
      910,
      1047,
      1070,
      1258,
      1390,
      1399,
      1494,
      1598,
      1614
    ],
    "through": "2026-06-30"
  },
  {
    "year": 2026,
    "quarter": 3,
    "trades": 1305,
    "avgReturnPct": 0.98,
    "lostAt": [
      333,
      339,
      345,
      402,
      522,
      775,
      797,
      923
    ],
    "through": "2026-09-16"
  }
];
